//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPGM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDistrict
    {
        public int DistrictID { get; set; }
        public string DistrictCode { get; set; }
        public string StateCode { get; set; }
        public string DistrictName { get; set; }
        public string PDName { get; set; }
        public string PDMobile { get; set; }
        public string PDAddress { get; set; }
        public string PDEmail { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
