//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPGM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSector
    {
        public int SectorID { get; set; }
        public string SectorCode { get; set; }
        public string SectorName { get; set; }
        public string StateCode { get; set; }
        public string DistrictCode { get; set; }
        public string ProjectCode { get; set; }
        public string SupName { get; set; }
        public string SupMobile { get; set; }
        public string SupAddress { get; set; }
        public string SupEmail { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int CenterTypeID { get; set; }
    }
}
