//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPGM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWGetSector
    {
        public int SectorID { get; set; }
        public string SectorCode { get; set; }
        public string SectorName { get; set; }
        public string ProjectName { get; set; }
        public string DistrictName { get; set; }
    }
}
